### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by juliohq** [adoroburrito/poorguelike#1]
This issue started since a42fd99, so I would suggest to drop the refactor branch for now then reopening this again in the future.

**Comment by adoroburrito** [comment]
Hi

branch `main` still seems to be working fine:
![image](https://user-images.githubusercontent.com/6116453/171966254-7ef96f3e-ca9c-4aac-bce7-9a684f3f59de.png)

that `refactor` branch is not ready yet... i've been coding it bit by bit on my spare time :)

(Take a look at the commits, i've been focusing on other logic + refactoring for now, i plan on doing drawing when i finish those!)
